name: Run SSM Bash Scripts and Test

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  run-and-test-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: 
          - "/vultara/"
          # - "soc"
          # - "consulting"
        deployment_type:
          # - "internalVultara"
          # - "prodConsulting"
          - "/trial/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Debug - Check matrix variables
        run: |
          echo "App: ${{ matrix.app }}"
          echo "Deployment Type: ${{ matrix.deployment_type }}"

      - name: Replace config.js values
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "${{ matrix.app }}" "${{ matrix.deployment_type }}" "./config.js"
          cat config.js

      - name: Replace environment.awsdeploy.ts file
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "${{ matrix.app }}" "${{ matrix.deployment_type }}" "./enviroment.awsdeploy.ts"
          cat enviroment.awsdeploy.ts

      - name: Replace serverless.yml file
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "/${{ matrix.app }}/" "/${{ matrix.deployment_type }}/" "./serverless.yml"
          cat serverless.yml
