name: Run SSM Bash Scripts and Test

on:
  workflow_dispatch:
      
  push:
    branches:
      - master

jobs:
  run-and-test-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment_path:
           - "/internalVultara/"
           - "/prodConsulting/"
           - "/trial/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Call replace_with_ssm_parameters function
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "${{ matrix.environment_path }}" "./config.js"
          cat config.js

      - name: Call replace_with_ssm_parameters function
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "${{ matrix.environment_path }}" "./enviroment.awsdeploy.ts"
          cat enviroment.awsdeploy.ts

      - name: Call replace_with_ssm_parameters function
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "${{ matrix.environment_path }}" "./serverless.yml"
          cat serverless.yml