name: Run SSM Bash Scripts and Test

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  run-and-test-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: 
          - "vultara"
        deployment_type:
          - "trial"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: update config values
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "/${{ matrix.app }}/" "/${{ matrix.deployment_type }}/" "./config.js"
          cat config.js

      - name: update environment.awsdeploy.ts values
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "/${{ matrix.app }}/" "${{ matrix.deployment_type }}/" "./enviroment.awsdeploy.ts"
          cat enviroment.awsdeploy.ts

      - name: update serverless.yml values
        run: |
          source ./ssm_change_value.sh
          replace_with_ssm_parameters "/${{ matrix.app }}/" "${{ matrix.deployment_type }}/" "./serverless.yml"
          cat serverless.yml

      - name: Send a notification about the failure.
        if: failure()
        run: |
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:837491041518:DevOps_notifications" \
          --message "The workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}" \
          --subject "${{ github.workflow }} Workflow Status is ${{ job.status }}"